on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    uses: exponentialcherub/deploy-pi/.github/workflows/deploy-pi.yml
    with:
      app-name: "whatsapp-listener"
      startup-cmd: "node index.js prod"
      branch: "main"
    secrets: inherit
